@extends('layouts.app')
@section('content')
<section class="fin-dashboard">
  <header class="fin-page-head"><div><small>{{ now()->format('l, d F Y') }}</small><h1>Welcome back, {{ auth()->user()->firstname }}</h1></div><div class="fin-head-actions"><button aria-label="Search"><i class="bi bi-search"></i></button><button aria-label="Filters"><i class="bi bi-sliders2-vertical"></i></button><span><i class="bi bi-calendar3"></i>{{ now()->startOfWeek()->format('d') }}–{{ now()->endOfWeek()->format('d M, Y') }}</span></div></header>
  <div class="fin-top-grid">
    <article class="fin-card fin-balance-card balance-privacy"><div class="fin-card-label">Total balance <span class="fin-select">{{ $general->cur_text }} <i class="bi bi-chevron-down"></i></span></div><div class="fin-balance"><span class="balance-value"><span>{{ $general->cur_sym }}</span><livewire:partials.balance /></span><button type="button" data-balance-toggle aria-label="Hide balance" aria-pressed="false"><i class="bi bi-eye"></i></button></div><p class="fin-growth"><i class="bi bi-graph-up-arrow"></i> +{{ number_format($perc['tradeWon_last_week_percentage'] ?? 0) }}% performance this week</p><div class="fin-actions"><a class="primary" href="{{ route('user.wallet.index') }}"><i class="bi bi-plus-circle"></i>Add money</a><a href="{{ route('user.wallet.index') }}"><i class="bi bi-arrow-up-right-circle"></i>Send money</a><a href="{{ route('user.wallet.index') }}"><i class="bi bi-wallet2"></i>Request money</a></div></article>
    <article class="fin-card fin-trend-card green"><div class="fin-card-label">Trading profit</div><svg viewBox="0 0 260 105" preserveAspectRatio="none"><path class="fill" d="M0 100 C55 100 75 94 105 70 S155 14 195 19 S230 12 260 4 L260 105 L0 105Z"/><path d="M0 100 C55 100 75 94 105 70 S155 14 195 19 S230 12 260 4"/><circle cx="133" cy="45" r="4"/></svg><strong>{{ $general->cur_sym }}{{ number_format($tradeWon, 2) }}</strong><p class="fin-growth"><i class="bi bi-graph-up-arrow"></i>{{ number_format($perc['tradeWon_last_week_percentage'] ?? 0) }}% <span>this week</span></p></article>
    <article class="fin-card fin-trend-card coral"><div class="fin-card-label">NFT holdings</div><svg viewBox="0 0 260 105" preserveAspectRatio="none"><path class="fill" d="M0 95 C45 90 88 94 118 67 S180 20 208 38 S234 19 260 15 L260 105 L0 105Z"/><path d="M0 95 C45 90 88 94 118 67 S180 20 208 38 S234 19 260 15"/><circle cx="172" cy="29" r="4"/></svg><strong>{{ $general->cur_sym }}{{ number_format($user->nft_balance, 2) }}</strong><p class="fin-growth"><i class="bi bi-graph-up-arrow"></i>{{ $transaction }} <span>transactions</span></p></article>
  </div>
  <div class="fin-main-grid">
    <article class="fin-card fin-payment-card balance-privacy"><div class="fin-card-label">Portfolio overview</div><div class="fin-overview-total"><strong class="balance-value">{{ $general->cur_sym }}{{ number_format($deposit - $withdraw, 2) }}</strong><button type="button" data-balance-toggle aria-label="Hide balance" aria-pressed="false"><i class="bi bi-eye"></i></button></div><p class="fin-growth"><i class="bi bi-graph-up-arrow"></i> +{{ number_format($perc['tradeWon_last_week_percentage'] ?? 0) }}% account performance</p><div class="fin-overview-stats"><div><span>Total deposits</span><strong>{{ $general->cur_sym }}{{ number_format($deposit, 0) }}</strong></div><div><span>Total withdrawals</span><strong>{{ $general->cur_sym }}{{ number_format($withdraw, 0) }}</strong></div><div><span>Net trade gain</span><strong>{{ $general->cur_sym }}{{ number_format($tradeWon, 0) }}</strong></div></div><div class="fin-year-chart">@foreach([42,54,39,66,78,51,93,62,46,72,58,83,69,49,75,55,88,64,44,71,59,80,67,53,74,48,61,86] as $index => $height)<i style="--h:{{ $height }}%" class="{{ $index >= 16 && $index <= 19 ? 'selected' : '' }}"></i>@endforeach</div><div class="fin-year-labels"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span class="active">May</span><span>Jun</span><span>Jul</span><span>Aug</span></div></article>
    <article class="fin-card fin-earning-card balance-privacy"><div class="fin-card-label">Earning overview <a href="{{ route('user.transaction.log') }}">View activity <i class="bi bi-arrow-up-right"></i></a></div><div class="fin-overview-total"><strong class="balance-value">{{ $general->cur_sym }}{{ number_format($tradeWon, 2) }}</strong><button type="button" data-balance-toggle aria-label="Hide balance" aria-pressed="false"><i class="bi bi-eye"></i></button></div><p class="fin-growth"><i class="bi bi-graph-up-arrow"></i> {{ $tradeWin }} wins from {{ $tradeLog }} trades</p><div class="fin-bar-chart">@foreach([72,48,20,58,79,84,34,69,62,55,63,58,48,20,57,67,81,74,39,61,54,78,69,42,65,52,72,88,76,64,58,45,70,52,61,39] as $index => $height)<i style="--h:{{ $height }}%" class="{{ $index >= 20 && $index <= 23 ? 'active' : '' }}"></i>@endforeach<div class="fin-chart-tip"><small>{{ now()->format('M, Y') }}</small><strong>{{ $general->cur_sym }}{{ number_format($tradeWon, 2) }}</strong></div></div><div class="fin-months"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span></div></article>
  </div>
  <div class="fin-bottom-grid">
    <article class="fin-card"><div class="fin-card-label">Trade performance <a href="{{ route('user.practice.contract.log') }}">View all</a></div><div class="fin-mini-kpis"><div><i class="bi bi-collection"></i><strong>{{ $tradeLog }}</strong><span>Total trades</span></div><div><i class="bi bi-arrow-up-right"></i><strong>{{ $tradeWin }}</strong><span>Winning</span></div><div><i class="bi bi-slash-lg"></i><strong>{{ $tradeDraw }}</strong><span>Draw</span></div><div><i class="bi bi-arrow-down-right"></i><strong>{{ $tradeLose }}</strong><span>Losing</span></div></div></article>
    <article class="fin-card fin-recent"><div class="fin-card-label">Recent contracts</div>@forelse($tradelogs->take(4) as $tradelog)<div class="fin-contract-row"><span class="{{ $tradelog->result == 1 ? 'win' : ($tradelog->result == 2 ? 'loss' : 'pending') }}"><i class="bi bi-{{ $tradelog->hilow == 1 ? 'arrow-up-right' : 'arrow-down-right' }}"></i></span><div><strong>{{ optional($tradelog->crypto)->name ?? 'Digital asset' }}</strong><small>{{ $tradelog->created_at->diffForHumans() }}</small></div><b>{{ $tradelog->result == 1 ? '+' : ($tradelog->result == 2 ? '-' : '') }}{{ $general->cur_sym }}{{ number_format($tradelog->amount, 2) }}</b></div>@empty<p class="fin-empty">No contracts recorded yet.</p>@endforelse</article>
  </div>
</section>
@endsection
